### ISSUE TITLE
support for play json lib

### ISSUE THREAD

**Issue by chenbekor** [gatling/jsonpath#14]
hi - I would like to explore the possibility of using this library from with play framework (scala). Since play uses it's own json library I wonder if I can somehow use this library integrated with play json lib.

**Comment by slandelle** [comment]
Supporting other usages would only makes changes and maintenance (breaking changes, compatibility) more complex, without any benefit for Gatling.
So, that's a no.
But you can find a [wrapper](https://github.com/josephpconley/play-jsonpath).
