### ISSUE TITLE
jsonPath parse error ["1","2","3"]

### ISSUE THREAD

**Issue by YordanBorisov** [gatling/jsonpath#24]
JsonPath do not find anything when try to parse Json array in ChainBuilder exec

http("List")
        .get(URL + "/list")
        .check(status.is(200))
        .check(jsonPath("$[*]").ofType[Map[String, Any]].findAll.saveAs("data")

**Comment by slandelle** [comment]
This is a JSON array, hence a Seq, not a JSON object that could be turned into a Map.

**Comment by YordanBorisov** [comment]
Can you please show me how can I do it.

**Comment by YordanBorisov** [comment]
@slandelle I fix the problem 3 days before by spliting the string in array and replace the '['and ']' charactersbut now again I have this json array
The strange thing is that every JsonPath library ,website is parsing successfully the json array but not the gatling/jsonpath. Please follow this http://jsonpath.com/ and https://github.com/jayway/JsonPath
