### ISSUE TITLE
jsonPath parse error ["1","2","3"] or [{"a":"1","b":"2","c":"3"},{"a":"1","b":"2","c":"3"},{"a":"1","b":"2","c":"3"}]

### ISSUE THREAD

**Issue by YordanBorisov** [gatling/jsonpath#25]
So 
JsonPath do not find anything when try to parse Json array in ChainBuilder exec

http("List")
.get(URL + "/list")
.check(status.is(200))
.check(jsonPath("$[*]").ofType[Map[String, Any]].findAll.saveAs("data")
and this is a JSONArray not JSON object that is why is not working

The solution which I found is  spliting the string in array and replace the '['and ']' characters but now again I have this json array

The strange thing is that every JsonPath library ,website is parsing successfully the json array but not the gatling/jsonpath. Please follow this http://jsonpath.com/ and https://github.com/jayway/JsonPath
Also the new json is in this follow format : [{"a":"1","b":"2","c":"3"},{"a":"1","b":"2","c":"3"},{"a":"1","b":"2","c":"3"}]
I think gatling/jsonpath must provide functonality to fetch json array also

**Comment by slandelle** [comment]
If what yo have is a JSON array and not a JSON object, you have to use `ofType[Seq[Any]]`

**Comment by slandelle** [comment]
If you still think there's an issue, please provide a JSON payload input.
