### ISSUE TITLE
Issue when root element is an array

### ISSUE THREAD

**Issue by KieranPringle** [gatling/jsonpath#26]
Given the following structure:
```json
[  
   {  
      "id":"uniqueId1",
      "poNumber":"uniquePoNumber1",
      "purchaseItems":[  
         {  
            "id":"purchaseItemId",
            "quantity":1,
            "unpaidQuantity":1,
            "productInfo":{  
               "productName":"thing",
               "productCode":"CODE"
            }
         }
      ]
   },
   {  
      "id":"uniqueId2",
      "poNumber":"uniquePoNumber2",
      "purchaseItems":[  
         {  
            "id":"purchaseItemId",
            "quantity":1,
            "unpaidQuantity":1,
            "productInfo":{  
               "productName":"thing",
               "productCode":"CODE"
            }
         }
      ]
   }
]
```

This valid expression returns nothing: `$.[?(@.poNumber == '${po_number}')].id`, while this invalid expression does return the expected result `$[*][?(@.poNumber == '${po_number}')].id`.

Truthfully, I think that the second one seems more correct since the root element is an array, but it fails in all jsonPath testers I have tried while the first works in all.

**Comment by slandelle** [comment]
Sadly, "valid" and "invalid" are subject to interpretation when it comes to JsonPath. The original source is a mere blog post, not a spec, and all the more not a TCK. Most implementations, in particular those in PHP and Javascript (not directed toward those languages) you can find in online evaluators, are utter crap.

As you said, the second expression makes more sense than the former one as the root element is an array.
I'm not sure accepting the first one too would make sense. If you have some opinion and valid arguments, we can discuss it here.

**Comment by slandelle** [comment]
Correcting myself: neither `$.[?(@.poNumber == '${po_number}')].id` nor `$[*][?(@.poNumber == '${po_number}')].id` work and this is expected.

> []: subscript operator. XPath uses it to iterate over element collections and for predicates. In Javascript and JSON it is the native array operator.

In our interpretation, the subscript must be performed on the item (an array, or an object which is just an array of (key, value) pairs), hence in your case on the root itself: `$[?(@.poNumber == '${po_number}')].id`.

Closing as "won't fix". As I said, in the absence of a proper spec, one can only interpret, and sadly sometimes interpretations diverge.

**Comment by KieranPringle** [comment]
Thanks for the response. You will find that the second one does work though. Thanks for the better version though, that works just fine and makes more sense than my now obviously wrong expression.
