### ISSUE TITLE
Unable to extract the json data with key having the space.

### ISSUE THREAD

**Issue by Pavangu31** [gatling/jsonpath#28]
I have the below JSON in the response.

i am trying 
.check(jsonPath("$.store.book data[*].category").findAll.saveAs("category")) 

Unfortunately it is not working. Also i tried below as well. it is not working.
.check(jsonPath("$.store.'book data'[*].category").findAll.saveAs("category")) 
.check(jsonPath("$.store.['book data'[*]].category").findAll.saveAs("category")) 

   { "store": {
        "book data": [ 
          { "category": "reference",
            "author": "Nigel Rees",
            "price": 8.95
          },
          { "category": "fiction",
            "author": "Evelyn Waugh",
            "price": 12.99
          },
          { "category": "fiction",
            "author": "Herman Melville",
            "price": 8.99
          },
          { "category": "fiction",
            "author": "J. R. R. Tolkien",
            "price": 22.99
          }
        ],
        "bicycle": {
          "color": "red",
          "price": 19.95
        }
      }
    }

Please suggest

**Comment by slandelle** [comment]
Please use the Gatling mailing list for questions, not the bug tracker.
