### ISSUE TITLE
Is it possible to add the dependency configuration example for different build tools in readme.

### ISSUE THREAD

**Issue by magicliang** [gatling/jsonpath#31]
Actually from the readme, user don't know how to introduce this tool in different build tools including sbt/mavan/gradle.

I have a project powered by maven, I figured out the dependency element myself like this:

        <dependency>
            <groupId>io.gatling</groupId>
            <artifactId>jsonpath_2.12</artifactId>
            <version>0.6.10</version>
        </dependency>

New users to this lib will be grateful if you have dependency configuration example snippets for popular build tools.

**Comment by slandelle** [comment]
This is more of a build tools newbie issue than an issue for this library.
All this information you're looking fo is available on `search.maven.org` which is the web interface for maven central and I don't see a point in duplicating it here.
Also, you have a direct link on the maven central badge on the README.

**Comment by magicliang** [comment]
Actually the dependency element I pasted is my search result in central result, I know where and how to search for artifacts.  

I am a newbie to SBT so I am not sure how this artifact will be promoted into central repo. What is its group id, what is its artifact id?  I just can't tell them from the readme and *.sbt files.  

Per my experience, Java's lib(e.g. Spring/DropWizard and so forth) usually has a official website which including a get started section which includes dependency elements for different build tools. If they don't have an official website, the dependency elements are in the github readme. I haven't see a real-world programmer search at repo at the beginning, they will always try to find official version in the get-started section or readme.md. Because there maybe libs with similar names and different versions in a search result list. It is really hard-to tell which jar is latest stable one.

This issue is just a suggestion.

**Comment by magicliang** [comment]
ha, I just realized the badge is clickable, I don't know that before.
