### ISSUE TITLE
missing scala 2.11 build, which totally break its compatibility

### ISSUE THREAD

**Issue by chenfanggm** [gatling/jsonpath#38]
Hi Gatling team,

Jsonpath lib missed its scala 2.11 build, which makes the whole application hard to be compatible with the majority library. Could you provide a 2.11 build? 

Thanks,
Chen

**Comment by slandelle** [comment]
Sorry but as explained in README, this library is solely intended for usage in Gatling.

**Comment by plokhotnyuk** [comment]
@chenfanggm have you tried [dijon](https://github.com/pathikrit/dijon)? It uses dynamic types for querying and updating JSON values and for JSON objects and arrays allows to use full power of Scala collection libraries, so it is much more handy to work with JSON than  JSONPath. Also, it is available for Scala 2.11
